//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebChess.WCFChess {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFChess.iChess")]
    public interface iChess {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iChess/InitializeBoard", ReplyAction="http://tempuri.org/iChess/InitializeBoardResponse")]
        bool InitializeBoard();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface iChessChannel : WebChess.WCFChess.iChess, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class iChessClient : System.ServiceModel.ClientBase<WebChess.WCFChess.iChess>, WebChess.WCFChess.iChess {
        
        public iChessClient() {
        }
        
        public iChessClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public iChessClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public iChessClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public iChessClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool InitializeBoard() {
            return base.Channel.InitializeBoard();
        }
    }
}
