///////////////////////////////////////////////////////////
//  Player.cs
//  Implementation of the Class Player
//  Generated by Enterprise Architect
//  Created on:      22-jun-2012 11:03:34
//  Original author: juliano
///////////////////////////////////////////////////////////




public class Player {

	private int _ID;
	private string _nickName;
	private string _password;

	public Player(){

	}

    public Player(string nickName, string password)
    {
        NickName = nickName;
        _password = password;
    }


	~Player(){

	}

	public virtual void Dispose(){

	}

	public int ID{
		get{
			return _ID;
		}
		set{
			_ID = value;
		}
	}

	public string NickName{
		get{
			return _nickName;
		}
		set{
			_nickName = value;
		}
	}

	public string Password{
		set{
			_password = value;
		}
	}

}//end Player